### ISSUE TITLE
[RFC] Should OverrideAudit check for/report "Non-Overrides"?

### ISSUE THREAD

**Issue by OdatNurd** [OdatNurd/OverrideAudit#16]
### Summary

Currently only files in the unpacked package directory that also exist inside of the `sublime-package` file that is currently being used by Sublime text are considered to be overrides and everything else is ignored.

It's conceivable that you might create an override for a file in a package, followed by the package author releasing a new version that deletes or renames the file that you were overriding. Now the file is no longer considered an override but could possibly cause problems.

As an (admittedly contrived) example, consider if a package had a python plugin that implemented one of its commands which you overrode to tweak something, and the author of the package renamed that file and added new features. 

Now on package update your file is no longer an override, so you get no notification. In the meantime depending on the names of the two versions of the file in question your version of the file may be loaded after the "official" one, clobbering the command away in favor of yours, which is making it act like an override even though it doesn't outwardly appear to.

If this is a concern, we could do something like:
  * Have a new report that tells you when there are loose files that don't correspond to anything
  * Include those files in the Override Report with something like `[?]` in front of them to indicate we don't know what they are
  * Something else?

**Comment by FichteFoll** [comment]
Imo these files should be included in the override report and annotated to be missing in the original. 

A remaining issue with this solution would be how freshening this override type should work, though.

**Comment by OdatNurd** [comment]
I favour that solution as well. I'm not sure what the best thing to do would be in the case of an expired override report though. If a package has no technically expired override but *does* have one of these suspect ones, should it appear in the report in that case?

My feeling on that would be yes as well (seems dangerous for at least the scenario I outlined above) but I don't know if there is some weird use case for augmenting an installed package by adding unrelated files to the `Packages` directory for it (instead of inside of your  `User` package). 

The only package I know of that may do something like this is Sublimerge 3, which plays weird games with creating its own overrides (and is the reason that the `ignore_overrides_in` setting exists). Presumably it's careful to remove files that it created but no longer needs, though.

I'm not sure that freshening such a file makes any sense in this case though. My inclination would be to leave it alone and let the user make the ultimate determination on whether to delete it or not. As currently implemented the freshen operation would leave it alone because it's not considered an override so there's no file to compare its date to.

**Comment by FichteFoll** [comment]
Extraneous files are usually an indication of the override being outdated as the file was removed in the original. 

The only situations where this fails are packages that generate files themselves (into an override package). InactivePanes also stores its generated color schemes in a subdirectory of itself. I would love to have a temporary location to put these in, but currently this seems like the best option. Better than SL polluting the user package anyway.

**Comment by OdatNurd** [comment]
Initial support for this has been implemented in `master` at 467b721b0bee8e629693c9fec131ad7c06d2c27c. Any files that appear in an unpacked package that is also associated with a `sublime-package` will now appear in the base OverrideAudit report annotated with `[?]` to indicate their status.

They're automatically excluded from freshening because only actual overrides are considered for this (due to requiring a base file to compare the time stamp against). They're also manually excluded from diff operations in the context menu and diffs in general for similar reasons, but you can open them for editing and you can delete them.

This currently occurs for all packages; possibly a setting akin to `ignore_overrides_in` could be added if needed to exclude packages from displaying these sorts of files, such as for packages that generate their own data files.

**Comment by OdatNurd** [comment]
This is now released in OverrideAudit 2.1. 

As currently implemented, these files will appear in diff reports (although they only report that they can't be diffed) since there are use cases for diff reports that involve vetting and gathering changes made to a package and in that case it would be handy to be reminded that they exist.

There's also a setting that turns this on or off (it defaults to on) and that setting can also be used to exclude (via regex) files that are probably uninteresting. The default is to ignore files in the `.git`, `.hg` and `.svn` directories.
