### ISSUE TITLE
[BUG] Bulk Diff report does not show new files

### ISSUE THREAD

**Issue by michaelblyons** [OdatNurd/OverrideAudit#30]
### Summary

I added a `Default.sublime-keymap` file to my unpacked ShellScript package, intending eventually to make a PR. At some point much later, I realized one of the rules was bugged and went to change it, but I didn't remember what `Default.sublime-keymap` was called.

OverrideAudit to the rescue! Bulk Diff the ShellScript package and it'll tell me which file I tinkered with! Except not quite: Since there is no `Default.sublime-keymap` in the original package, it doesn't appear in the diff at all.

### Expected Behaviour

New files in a package's folder are part of the diff.

### Actual Behaviour

Only existing ~packages~ [files] are diffed.

### How to Reproduce

1. Unpack ShellScript with your favorite method.
1. Add a new file to it.
1. Run an OverrideAudit bulk diff on the package.
1. New file is not listed.

### Environment

- Sublime Text build: [3190]
- OverrideAudit version: v[1.2.1]
- Operating System: [MacOS]
- Case Sensitive Filesystem: [?] Until _today,_ I thought it was CS, but the Git for Windows maintainer [says CI](https://github.com/git-for-windows/git/issues/2050#issuecomment-467793063).

**Comment by OdatNurd** [comment]
I think this use case is actually covered by #16; technically files that don't exist in the `sublime-package` file in use aren't overrides, although that doesn't mean that they can't still contribute to problems such as those outlined there or just the general surprise of files existing when you didn't expect them to.

My leanings on this are to proceed along the lines of the discussion in that issue; While creating a general override report, all of the loose files that aren't overrides should appear in the list with a `[?]` marker on them as an indication that they exist in the package but their state is unknown.

Along with that would (I think) be a new setting along the lines of `ignore_overrides_in` that could disable this particular feature on a package by package basis to allow for less noise in reports when you use a package that generates files like this (such as the  `Sublimerge` packages do).

**Comment by michaelblyons** [comment]
Agreed, this is nominally a duplicate of #16, and I think I'm on board with most of the discussion there.

**Comment by OdatNurd** [comment]
Initial support has been added for this in `master` at 467b721b0bee8e629693c9fec131ad7c06d2c27c; as noted in #16 this adds files that exist in unpacked packages for which there is also a `sublime-package` file to the base override report annotated with `[?]` to indicate that the status of the file is unknown (not a technical override).

The contextual commands for diffing these files are not available, nor is the ability to freshen them. However the context menu allows you to open and delete them. 

This is currently done for any package that can contain overrides. Some packages intentionally generate their own data files into unpacked versions of themselves, so this may be a bit noisy. Sublimerge 3 and Sublimerge Pro are examples of this, as is InactivePanes.

The `ignore_overrides_in` setting will exclude such packages from the override report in general; if needed a new setting to only disallow tracking of these files could be implemented. It's unclear yet whether this is needed or not.

**Comment by OdatNurd** [comment]
This is now released as a part of OverrideAudit 2.1.0. The final form of this is changed from the above; files of this type will appear in diff reports, though they report that they can't be diffed. 

There's a new setting that turns this on or off, and it also allows you to filter files away so that they aren't seen. This is done for the control directories for some popular version control systems, for example.
