### ISSUE TITLE
[BUG] Does not report overrides with coerced Package names

### ISSUE THREAD

**Issue by michaelblyons** [OdatNurd/OverrideAudit#33]
### Summary

I have a package installed that mimics the name of another package. I do not see overrides between the original (which is effectively being partly overridden) and this camouflaged package.

``` javascript
// Package Control.sublime-settings
"package_name_map":
{
    "real package name": "Package disguises itself as this"
},
```

### Expected Behaviour

Overrides are listed and diffable.

### Actual Behaviour

No overrides noticed

### How to Reproduce

1. Follow instructions at https://github.com/deathaxe/sublime-commands#package-control
1. Run OverrideAudit Rport
1. Notice no entry for "Default"

### Environment

- Sublime Text build: 4065
- OverrideAudit version: v2.2.0?
- Operating System: MacOS
- Case Sensitive Filesystem: Yes

**Comment by OdatNurd** [comment]
Hmm interesting; I would consider that a sort of "package alias" that allows the contents of one package to be considered as part of another. I'm not sure offhand how that might affect the underlying data structures that are used to track the contents of packages and determine what's an override, but I don't think it would be too hairy.

There are likely other places where this sort of information would be useful to know as well, such as in the hover popup.

**Comment by michaelblyons** [comment]
Maybe it was my fault. I went through the steps again, and this time the files were put in `Default` where OA correctly picked them up for the report.
