### ISSUE TITLE
[BUG] Symbolic linked directory not applying if it's from a directory within Data that starts with the name "Packages"

### ISSUE THREAD

**Issue by God-damnit-all** [OdatNurd/OverrideAudit#38]
### Summary

Symbolic linked directory not applying if it's from a directory within Data that starts with the name "Packages"... at least on Windows, not sure about other OSes. This one is hard to explain, please refer to **How to Reproduce**

### Expected Behaviour

Overrides from within these directories should be applying.

### Actual Behaviour

Overrides from within these directories are not applied.

##### BROKEN
1. Run `git clone https://github.com/sublimehq/Packages "Packages [sublimehq]"` inside the Data directory (one level up from the Packages directory)
2. `mklink /D "%CD%\Packages\Python" "%CD%\Packages [sublimehq]\Python"`
3. Open `Packages\Python\Python.sublime-syntax`
4. Open the console with <kbd>Ctrl</kbd>+<kbd>`</kbd>
5. Save the file
6. The console <ins>**WON'T**</ins> say "generating syntax summary" as expected

* `rmdir "%CD%\Packages\Python"` to get rid of the symbolic link

##### Why it's related to the name of the directory within Data that houses the symbolic link:
1. Run `git clone https://github.com/sublimehq/Packages "Pkgs [sublimehq]"` inside the Data directory (one level up from the Packages directory)
2. `mklink /D "%CD%\Packages\Python" "%CD%\Pkgs [sublimehq]\Python"`
3. Open `Packages\Python\Python.sublime-syntax`
4. Open the console with <kbd>Ctrl</kbd>+<kbd>`</kbd>
5. Save the file
6. The console <ins>**WILL**</ins> say "generating syntax summary" as expected

### Environment

- Sublime Text build: 4183
- OverrideAudit version: v2.2.7
- Operating System: Windows
- Case Sensitive Filesystem: No

**Comment by FichteFoll** [comment]
This sounds like a Sublime Text issue (https://github.com/sublimehq/sublime_text/issues/) rather than an issue with OverrideAudit, since OA isn't involved in any of the steps for reproduction.

**Comment by OdatNurd** [comment]
Indeed, I would tend to agree. OA only examines the contents of packages to
tell you if there are changes. It has no effect on what file is eventually
loaded since that's the job of the core.

If you link such a file and then modify it, does OA notice the change even
if sublime doesn't?
