### ISSUE TITLE
Override: Date Inspection

### ISSUE THREAD

**Issue by OdatNurd** [OdatNurd/OverrideAudit#6]
Perform an inspection to check to see if any overrides in use are "out of date" due to their being older than the files that they are overriding. This would work not only for a complete override but also single unpacked override files.

The report should call out overrides which may need to be rethought/recreated/removed so as not to block incoming changes.

 * [x] Generate report on demand via command palette/menu
 * [x] Generate report when plugin is loaded (i.e. at startup of Sublime)
 * ~~~[ ] Generate report once per day (for extended sessions) if any override is expired~~~
 * [x] ~~~Hook into Package Control if installed~~~ Listen for changes to `ignored_packages` to notice when a package is probably being installed or updated, and generate a report if anything is out of date

~~~That last one I'm going to say is optional because I'm not sure if it's possible to do something like that at the moment. My vague understanding is that I may only be able to detect when my own plugin is being updated and not someone else's but I am not sure.~~~

The last item in the list has been swapped for listening to changes in the standard preferences changing so that we can see when a file is being added and removed from the `ignored_packages` setting. This is something that PackageControl does when it installs or updates packages, so this seems like a good time to generate a potential report.

Additionally, the item for generating a report once per day for an extended session has been removed. The idea currently is that with reports happening every time a package upgrades and whenever the sublime version changes, there is no need for an ongoing automated report; any changes that happen during a session are most likely something you're doing outside the auspices of Package Control, so you probably know what you're doing.

**Comment by OdatNurd** [comment]
As of commit a17890627f3a1704ba96e25ce17f9744a8de3a2c OverrideAudit now has the ability to generate an override report which contains information on overrides that are out of date (or expired, in the lingo I just made up on the fly because that's how I roll) or optionally an override report that ONLY displays expired overrides.

The idea is that one of these two commands would be triggered at set times to perform the automated checking.

**Comment by OdatNurd** [comment]
As of commit 9e37ee1d4da78c3e157197e956e8b037019ce9da OverrideAudit now notices when packages are removed from the list of ignored packages, and then automatically generates a report after a (user configurable) delay period. Changes in the list of ignored packages will reset the countdown, while putting all removed packages back will cancel the report entirely.

This happens for all package unignores; this will catch when PackageControl is upgrading and installing packages as well as when the user is re-enabling on their own. The idea is that aside from package upgrades, re-enabling a package after some time may bring into play overrides that previously did not worry you but which now need to be taken care of.

In a future version these scenarios could possibly be dialed in to be uniquely configurable, but I am going to defer that to a potential post-release update.

**Comment by OdatNurd** [comment]
As of commit 4fe9839b8e12095eacb2f657f34f8c8f3a6f9c5a there is now support for generating an expired override report when the plugin is loaded.

More specifically, we now store a status file that records the last known Sublime version number as well as an indication if we were waiting for an automatic report to trigger due to a package being removed from the ignored packages list.

When the plugin is loaded, if the sublime version has changed or if there was a pending automatic report, a report is triggered right away. This catches overrides that become expired due to an upgrade of Sublime itself, as well as from a package upgrade that requires Sublime to restart before the report triggers.

This closes out the issue, although we may want to revisit this in the future to e.g. add additional options for scheduling an automatic report, allow them to be disabled completely, etc.

**Comment by FichteFoll** [comment]
The proper commit should be https://github.com/OdatNurd/OverrideAudit/commit/8bda3dae3037ee3951beaecf37e376451e3395db.

**Comment by OdatNurd** [comment]
Ahh thanks!
